version: '3.8'

services:

  database:
    image: postgres:15.1-alpine
    restart: always
    container_name: postgres_database
    expose:
      - "5432"
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    env_file:
      - .env_docker
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 20s
      retries: 5

  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    networks:
      - my_network
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8800:80"
    env_file:
      - .env_docker

networks:
  my_network:
    name: my_network

volumes:
  pgdata:
    name: pgdata
